from __future__ import annotations

import io
from typing import Literal

SECTION_TITLES = [
    ("bottlenecks", "Bottlenecks"),
    ("risks", "Risks"),
    ("missingSteps", "Missing Steps"),
    ("recommendations", "Recommendations"),
    ("automationOpportunities", "Automation Opportunities"),
]

ExportFormat = Literal["md", "docx", "pdf"]


def _safe_list(report: dict, key: str) -> list[str]:
    val = report.get(key) or []
    return [str(v) for v in val if str(v).strip()]


def render_markdown(report: dict, process_name: str | None = None) -> str:
    lines: list[str] = ["# Process Review Report"]
    if process_name:
        lines.append(f"**Process:** {process_name}")
    lines.append(f"**Health Score:** {report.get('healthScore', '-')}/100 ({report.get('band', '-')})")
    lines.append("")
    lines.append("## Summary")
    lines.append(report.get("summary") or "_No summary available._")
    for key, title in SECTION_TITLES:
        items = _safe_list(report, key)
        lines.append("")
        lines.append(f"## {title}")
        if not items:
            lines.append("_None identified._")
        else:
            lines.extend(f"- {it}" for it in items)
    lines.append("")
    lines.append("---")
    lines.append("_Generated by BPMN Copilot_")
    return "\n".join(lines)


def render_docx(report: dict, process_name: str | None = None) -> bytes:
    from docx import Document
    from docx.shared import Pt, RGBColor

    doc = Document()
    doc.add_heading("Process Review Report", level=1)

    if process_name:
        p = doc.add_paragraph()
        p.add_run("Process: ").bold = True
        p.add_run(process_name)

    p = doc.add_paragraph()
    p.add_run("Health Score: ").bold = True
    score = report.get("healthScore", "-")
    band = report.get("band", "-")
    run = p.add_run(f"{score}/100 ({band})")
    if isinstance(score, (int, float)):
        run.font.color.rgb = (
            RGBColor(0x10, 0x98, 0x61) if score >= 90 else
            RGBColor(0xCA, 0x8A, 0x04) if score >= 70 else
            RGBColor(0xDC, 0x26, 0x26)
        )

    doc.add_heading("Summary", level=2)
    doc.add_paragraph(report.get("summary") or "No summary available.")

    for key, title_text in SECTION_TITLES:
        items = _safe_list(report, key)
        doc.add_heading(title_text, level=2)
        if not items:
            para = doc.add_paragraph("None identified.")
            para.runs[0].italic = True
        else:
            for it in items:
                doc.add_paragraph(it, style="List Bullet")

    footer = doc.add_paragraph()
    footer.add_run("Generated by BPMN Copilot").italic = True
    footer.runs[0].font.size = Pt(9)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


_PDF_SAFE_REPLACEMENTS = {
    "\u2014": "-", "\u2013": "-",     
    "\u2018": "'", "\u2019": "'",      
    "\u201c": '"', "\u201d": '"',      
    "\u2026": "...",                    
    "\u20ac": "EUR",                  
    "\u2022": "-",                      
}


def _pdf_safe(text: str) -> str:
    """The PDF core font (Helvetica) only supports Latin-1. German umlauts
    (a/o/u-umlaut, sharp s) are within Latin-1 and render fine; a handful of
    'smart' punctuation marks and the euro sign are not, so map those to safe
    equivalents, then fall back to replacing anything else rather than crashing."""
    for bad, good in _PDF_SAFE_REPLACEMENTS.items():
        text = text.replace(bad, good)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def render_pdf(report: dict, process_name: str | None = None) -> bytes:
    from fpdf import FPDF
    from fpdf.enums import XPos, YPos

    pdf = FPDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    def h1(text: str):
        pdf.set_font("Helvetica", "B", 18)
        pdf.set_text_color(20, 25, 35)
        pdf.multi_cell(0, 10, _pdf_safe(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(1)

    def h2(text: str):
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(20, 25, 35)
        pdf.ln(2)
        pdf.multi_cell(0, 8, _pdf_safe(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def body(text: str, italic: bool = False):
        pdf.set_font("Helvetica", "I" if italic else "", 11)
        pdf.set_text_color(60, 66, 78)
        pdf.multi_cell(0, 6, _pdf_safe(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def bullet(text: str):
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(30, 35, 45)
        pdf.multi_cell(0, 6, _pdf_safe(f"-  {text}"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    h1("Process Review Report")
    if process_name:
        body(f"Process: {process_name}")

    score = report.get("healthScore", "-")
    band = report.get("band", "-")
    pdf.set_font("Helvetica", "B", 12)
    if isinstance(score, (int, float)):
        color = (16, 152, 97) if score >= 90 else (202, 138, 4) if score >= 70 else (220, 38, 38)
    else:
        color = (60, 66, 78)
    pdf.set_text_color(*color)
    pdf.multi_cell(
        0, 7, _pdf_safe(f"Health Score: {score}/100 ({band})"),
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )

    h2("Summary")
    body(report.get("summary") or "No summary available.")

    for key, title_text in SECTION_TITLES:
        items = _safe_list(report, key)
        h2(title_text)
        if not items:
            body("None identified.", italic=True)
        else:
            for it in items:
                bullet(it)

    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(140, 140, 140)
    pdf.multi_cell(0, 5, "Generated by BPMN Copilot", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return _pdf_output_bytes(pdf)


def _pdf_output_bytes(pdf) -> bytes:
    """Robustly get PDF bytes across fpdf2 versions and the legacy PyFPDF API."""
    out = None
    try:
        out = pdf.output()
    except TypeError:
        out = None
    if out is None or (isinstance(out, str) and not out):
        out = pdf.output(dest="S")
    if isinstance(out, str):
        return out.encode("latin-1", errors="replace")
    return bytes(out)


def render_review(report: dict, fmt: ExportFormat, process_name: str | None = None) -> tuple[bytes, str, str]:
    """Returns (file_bytes, filename, media_type)."""
    safe_name = "".join(c if c.isalnum() else "_" for c in (process_name or "process_review")).strip("_") or "process_review"
    if fmt == "md":
        text = render_markdown(report, process_name)
        return text.encode("utf-8"), f"{safe_name}.md", "text/markdown"
    if fmt == "docx":
        data = render_docx(report, process_name)
        return data, f"{safe_name}.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    if fmt == "pdf":
        data = render_pdf(report, process_name)
        return data, f"{safe_name}.pdf", "application/pdf"
    raise ValueError(f"Unsupported export format: {fmt}")
